version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: bulkbridge_postgres
    environment:
      POSTGRES_DB: bulkbridge
      POSTGRES_USER: bulkbridge
      POSTGRES_PASSWORD: bulkbridge_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./be/database/init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - bulkbridge_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bulkbridge -d bulkbridge"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis for caching and queues
  redis:
    image: redis:7-alpine
    container_name: bulkbridge_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - bulkbridge_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend Laravel Application
  backend:
    build:
      context: ./be
      dockerfile: Dockerfile
    container_name: bulkbridge_backend
    env_file:
      - docker.env
    volumes:
      - ./be:/var/www/html
      - backend_storage:/var/www/html/storage
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - bulkbridge_network
    restart: unless-stopped

  # Frontend React Application
  frontend:
    build:
      context: ./fe
      dockerfile: Dockerfile
    container_name: bulkbridge_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - bulkbridge_network
    restart: unless-stopped

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: bulkbridge_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites:/etc/nginx/sites-available
      - ./docker/nginx/ssl:/etc/nginx/ssl
    depends_on:
      - backend
      - frontend
    networks:
      - bulkbridge_network
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  backend_storage:
    driver: local

networks:
  bulkbridge_network:
    driver: bridge